### ISSUE TITLE
Support for Jetson Xavier NX

### ISSUE THREAD

**Issue by maxritter** [balena-os/balena-jetson#61] opened 2020-04-27 22:16 UTC
Would be great to have the new xavier nx supported as well! Jetpack 4.4 (developer edition) is out that has the drivers ;)

**Comment by acostach** [comment] 2020-04-30 08:52
Hi Max, looks like the meta-tegra layer does not yet support the NX machine, but there is a ticket there stating it will be added soon. 

Are you using the NX with the B01 Nano devkit carrier board? Or maybe know if it's fully compatible, apart from the known power limitations?

**Comment by maxritter** [comment] 2020-04-30 08:58
Thanks for letting me know! So we will wait for the meta-tegra update then :)

We are waiting for an answer from Auvidea concerning the best option for a NX carrier board. Probably will be the JNX30 board. But yeah, the B01 should support the NX module as well, as long as it does not draw too much current I think.

**Comment by maxritter** [comment] 2020-05-04 16:19
@acostach  Meta-Tegra was updated recently and now has experimental support for Jetson Xavier NX eMMC module in Nano carrier board. Is this good enough to get us going?

**Comment by acostach** [comment] 2020-05-04 16:42
@maxritter I've asked Matt from meta-tegra in the nx ticket to confirm his setup so we can order the same hardware and investigate support for the NX.

**Comment by maxritter** [comment] 2020-05-04 17:11
Great, looking forward to it!

**Comment by dremsol** [comment] 2020-05-18 16:03
Probably you are aware but NVIDIA dropped a [NX devkit](https://developer.nvidia.com/embedded/jetson-xavier-nx-devkit), didn't see that one coming... Anyway, we will receive one tomorrow and start some testing.

**Comment by acostach** [comment] 2020-05-21 13:45
Yes, we received the module and B01 nano board and started investigating it.

Currently we encountered some issues caused by cboot, we will address them in https://github.com/balena-os/meta-balena/issues/1905 and will keep you updated here on the progress.

**Comment by dremsol** [comment] 2020-05-28 12:30
hi @acostach, what kind of NX device you will be supporting? The official NX devkit or NX eMMC module in dev kit or Nano carrier board?

We have everything in-house to contribute the `photon-xavier-nx` device which is based on the eMMC module. Do you have a suggestion on which machine to base upon?

**Comment by dremsol** [comment] 2020-06-04 18:27
@acostach we have preliminary support for photon-xavier-nx. We will hold with a PR until following is merged;
https://github.com/balena-os/balena-jetson/pull/74

**Comment by acostach** [comment] 2020-06-04 19:08
@dremsol perfect. I assume you were able to build on top of the nx machine in this PR, right?

**Comment by dremsol** [comment] 2020-06-04 19:16
That's correct. Would be nice if we can pull it in once both https://github.com/balena-os/balena-jetson/pull/74 and https://github.com/balena-os/balena-jetson/pull/75 are merged.

**Comment by JohnBetaCode** [comment] 2020-07-30 20:12
when it is estimated to have support for Xavier NX Jetpack 4.4?

**Comment by acostach** [comment] 2020-10-06 08:22
@JohnBetaCode an image with L4T 32.4.3 is now available for testing in the [staging dashboard](https://dashboard.balena-staging.com), it's the image version 2.58.3+rev3.

Can be flashed on the target using: https://github.com/balena-os/jetson-flash/pull/30

Closing ticket as support for the NX is available in production dashboard.

**Closed by acostach** 2020-10-06 08:22 UTC

**Comment by compiaffe** [comment] 2020-10-12 14:29
@acostach Apologies for raising a closed issue, but does the Xavier NX image also support the SD card version (aka devkit?).

**Comment by acostach** [comment] 2020-10-12 14:36
Hello @compiaffe,

No, this image only works for the NX emmc version.

**Comment by compiaffe** [comment] 2020-10-12 14:49
Thanks @acostach. Any plans to support the devkit and if yes, any place I can keep myself up to date?

**Comment by acostach** [comment] 2020-10-12 15:27
@compiaffe we don't have this particular version of the hardware so for the moment it's not on the list, but will let you know if we have an update

**Comment by acostach** [comment] 2020-10-19 14:32
@compiaffe the nx devkit (sd-card) is now on our list. Planning to start looking into it in the next few weeks, when the hardware arrives.

**Comment by acostach** [comment] 2020-11-02 12:20
@compiaffe the NX Devkit SD-CARD image is now available for testing at https://dashboard.balena-staging.com/
