### ISSUE TITLE
User wants meta-balena v2.79.3 for jetson

### ISSUE THREAD

**Issue by thgreasi** [balena-os/balena-jetson#176] opened 2021-05-28 11:16 UTC
Meta issue to track the changes initially done in:
See: https://github.com/balena-os/balena-jetson/pull/172 (now closed)
in order to get the meta-balena changes of v released for this DT:
See: https://github.com/balena-os/meta-balena/pull/2193

**Comment by acostach** [comment] 2021-06-16 11:05
Closing, it is a duplicate of the request in https://github.com/balena-os/balena-jetson/issues/166

The hostOS image v2.80.3+rev1 has been released and the user is aware of this. Further problems are debugged in https://jel.ly.fish/d46273c3-2d16-4a80-b3fb-52be338711a4

**Closed by acostach** 2021-06-16 11:05 UTC
